name: L0gg3r.Builder tests
on: push
jobs:
  LoggerBuilderTests:
    name: LoggerBuilderTests
    runs-on: ubuntu-latest
    steps:
    - &o0
      name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test src/L0gg3r.Builder/tests/LoggerBuilderTests/src/LoggerBuilderTests.csproj -c Release
  LogSinkBuilderTests:
    name: LogSinkBuilderTests
    runs-on: ubuntu-latest
    steps:
    - *o0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test src/L0gg3r.Builder/tests/LogSinkBuilderTests/src/LogSinkBuilderTests.csproj -c Release
