name: L0gg3r.LogSinks.Console.Base tests
on: push
jobs:
  ConsoleLogSinkBaseTests:
    name: ConsoleLogSinkBaseTests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test src/L0gg3r.LogSinks.Console.Base/tests/ConsoleLogSinkBaseTests/src/ConsoleLogSinkBaseTests.csproj -c Release
