name: L0gg3r tests
on: push
jobs:
  LoggerTests:
    name: LoggerTests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test src/L0gg3r/tests/LoggerTests/src/LoggerTests.csproj -c Release
  LoggerExtensionsTests:
    name: LoggerExtensionsTests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test src/L0gg3r/tests/LoggerExtensionsTests/src/LoggerExtensionsTests.csproj -c Release
