name: L0gg3r CI/CD

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
     - created

jobs:
  CreateTestWorkflow:
    name: "Create Test Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Setup Nuke"
        run: dotnet tool install --global Nuke.GlobalTool
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: "Build Test Workflow file"
        run: nuke CreateGithubTestWorkflow
  Tests:
    name: "Tests"
    uses: ./.github/workflows/Test-Jobs.yml
    needs: [CreateTestWorkflow]
